Importing required libraries

In [1]:
import numpy as np
import pandas as pd
from sklearn import preprocessing
from sklearn.feature_selection import f_regression
from sklearn.feature_selection import SelectKBest
from sklearn.metrics import mean_absolute_percentage_error
from statsmodels.stats.outliers_influence import variance_inflation_factor
from sklearn.datasets import make_regression
from sklearn import preprocessing
import re
import warnings
warnings.filterwarnings("ignore")
import time
import os
import joblib
import pickle

Reading file by specifying the path

In [2]:
os.getcwd()

'C:\\Users\\Riyaz Mehendi\\OneDrive - CriticalRiver Technologies Pvt. Ltd\\Desktop\\Retail_Sales_Forecast\\src\\models'

In [3]:
project_path='C:\\Users\\Riyaz Mehendi\\OneDrive - CriticalRiver Technologies Pvt. Ltd\\Desktop\\Retail_Sales_Forecast'
processed_data='data\\processed'
processed_file_name='Merged_Data.csv'

In [4]:
processed_file_path=os.path.join(project_path,processed_data,processed_file_name)

In [5]:
Test_Data=pd.read_csv(processed_file_path)

Genrating random 10 rows from Merged data

In [6]:
Test_Data=Test_Data.sample(n = 10)

In [7]:
Test_Data

,ProductCategory,SalesInThousandDollars,MonthlyNominalGDPIndexinMillion,MonthlyRealGDPIndexinMillion,CPI,unemploymentrate,CommercialBankInterestRateonCreditCardPlans,FinanceRateonPersonalLoansatCommercialBanks24MonthLoan,Earningsorwagesindollarsperhour,CottonMonthlyPriceUScentsperPoundlbs,...,Exports,Tempavg,DewPointavg,Humidityavg,SeaLevelPressavg,Visibilityavg,Windavg,Precipsum,Event,FederalHoliday
35,MenClothing,1081.0,15740.544526,15148.822195,248.307,8.5,12.36,10.36,23.22,95.45,...,10.650,6.500000,-0.566667,62.500000,1020.633333,14.666667,9.533333,3.386333,2,2
152,WomenClothing,4481.0,17630.354586,16133.049427,261.074,5.9,11.82,10.73,24.50,73.38,...,9.450,20.700000,12.800000,62.666667,1019.300000,14.900000,6.900000,1.042000,0,1
226,OtherClothing,1209.0,17053.738107,15841.758762,257.377,6.9,11.85,10.22,24.11,84.65,...,9.650,7.500000,-1.966667,53.066667,1021.400000,14.766667,10.033333,2.667333,0,2
158,WomenClothing,4294.0,17900.981857,16329.523792,259.647,5.4,11.98,9.85,25.04,69.35,...,10.250,3.516129,-6.096774,54.000000,1019.032258,12.935484,9.838710,3.868065,0,0
187,OtherClothing,897.0,15036.277627,14824.165770,241.569,9.5,13.59,10.71,22.55,90.35,...,14.525,25.433333,16.733333,63.233333,1014.966667,14.966667,8.133333,3.505667,0,0
196,OtherClothing,1027.0,15472.391289,14990.963816,248.073,9.0,12.89,11.37,23.06,165.52,...,15.020,17.384615,10.576923,71.000000,1014.307692,12.576923,9.307692,4.474615,1,1
129,WomenClothing,3168.0,16208.314757,15292.349860,254.277,7.8,11.95,10.37,23.52,81.95,...,10.875,14.645161,9.129032,71.387097,1014.193548,13.451613,7.903226,2.393548,1,1
237,OtherClothing,1153.0,17709.436967,16196.814474,260.500,5.7,11.82,10.73,24.52,70.34,...,9.450,15.129032,7.870968,62.774194,1013.322581,14.516129,8.322581,4.998387,1,1
180,OtherClothing,945.0,14613.991481,14551.024838,238.970,9.8,13.60,11.20,22.51,77.40,...,10.400,0.233333,-7.566667,57.600000,1014.533333,14.766667,11.633333,1.720667,0,2
56,MenClothing,681.0,16785.312189,15644.832268,258.504,7.2,11.88,10.13,24.16,90.09,...,9.650,20.066667,11.500000,60.300000,1016.566667,14.666667,6.366667,2.497667,0,1

In [8]:
Test_Data.reset_index(drop=True, inplace=True)

In [9]:
Test_Data

,ProductCategory,SalesInThousandDollars,MonthlyNominalGDPIndexinMillion,MonthlyRealGDPIndexinMillion,CPI,unemploymentrate,CommercialBankInterestRateonCreditCardPlans,FinanceRateonPersonalLoansatCommercialBanks24MonthLoan,Earningsorwagesindollarsperhour,CottonMonthlyPriceUScentsperPoundlbs,...,Exports,Tempavg,DewPointavg,Humidityavg,SeaLevelPressavg,Visibilityavg,Windavg,Precipsum,Event,FederalHoliday
0,MenClothing,1081.0,15740.544526,15148.822195,248.307,8.5,12.36,10.36,23.22,95.45,...,10.650,6.500000,-0.566667,62.500000,1020.633333,14.666667,9.533333,3.386333,2,2
1,WomenClothing,4481.0,17630.354586,16133.049427,261.074,5.9,11.82,10.73,24.50,73.38,...,9.450,20.700000,12.800000,62.666667,1019.300000,14.900000,6.900000,1.042000,0,1
2,OtherClothing,1209.0,17053.738107,15841.758762,257.377,6.9,11.85,10.22,24.11,84.65,...,9.650,7.500000,-1.966667,53.066667,1021.400000,14.766667,10.033333,2.667333,0,2
3,WomenClothing,4294.0,17900.981857,16329.523792,259.647,5.4,11.98,9.85,25.04,69.35,...,10.250,3.516129,-6.096774,54.000000,1019.032258,12.935484,9.838710,3.868065,0,0
4,OtherClothing,897.0,15036.277627,14824.165770,241.569,9.5,13.59,10.71,22.55,90.35,...,14.525,25.433333,16.733333,63.233333,1014.966667,14.966667,8.133333,3.505667,0,0
5,OtherClothing,1027.0,15472.391289,14990.963816,248.073,9.0,12.89,11.37,23.06,165.52,...,15.020,17.384615,10.576923,71.000000,1014.307692,12.576923,9.307692,4.474615,1,1
6,WomenClothing,3168.0,16208.314757,15292.349860,254.277,7.8,11.95,10.37,23.52,81.95,...,10.875,14.645161,9.129032,71.387097,1014.193548,13.451613,7.903226,2.393548,1,1
7,OtherClothing,1153.0,17709.436967,16196.814474,260.500,5.7,11.82,10.73,24.52,70.34,...,9.450,15.129032,7.870968,62.774194,1013.322581,14.516129,8.322581,4.998387,1,1
8,OtherClothing,945.0,14613.991481,14551.024838,238.970,9.8,13.60,11.20,22.51,77.40,...,10.400,0.233333,-7.566667,57.600000,1014.533333,14.766667,11.633333,1.720667,0,2
9,MenClothing,681.0,16785.312189,15644.832268,258.504,7.2,11.88,10.13,24.16,90.09,...,9.650,20.066667,11.500000,60.300000,1016.566667,14.666667,6.366667,2.497667,0,1

Creating Dataframe with only numeric columns

In [10]:
Test_Numeric = Test_Data.drop(['ProductCategory'], axis = 1)

In [11]:
Test_Numeric

,SalesInThousandDollars,MonthlyNominalGDPIndexinMillion,MonthlyRealGDPIndexinMillion,CPI,unemploymentrate,CommercialBankInterestRateonCreditCardPlans,FinanceRateonPersonalLoansatCommercialBanks24MonthLoan,Earningsorwagesindollarsperhour,CottonMonthlyPriceUScentsperPoundlbs,Changein,...,Exports,Tempavg,DewPointavg,Humidityavg,SeaLevelPressavg,Visibilityavg,Windavg,Precipsum,Event,FederalHoliday
0,1081.0,15740.544526,15148.822195,248.307,8.5,12.36,10.36,23.22,95.45,-8.82,...,10.650,6.500000,-0.566667,62.500000,1020.633333,14.666667,9.533333,3.386333,2,2
1,4481.0,17630.354586,16133.049427,261.074,5.9,11.82,10.73,24.50,73.38,-0.84,...,9.450,20.700000,12.800000,62.666667,1019.300000,14.900000,6.900000,1.042000,0,1
2,1209.0,17053.738107,15841.758762,257.377,6.9,11.85,10.22,24.11,84.65,-5.26,...,9.650,7.500000,-1.966667,53.066667,1021.400000,14.766667,10.033333,2.667333,0,2
3,4294.0,17900.981857,16329.523792,259.647,5.4,11.98,9.85,25.04,69.35,-0.70,...,10.250,3.516129,-6.096774,54.000000,1019.032258,12.935484,9.838710,3.868065,0,0
4,897.0,15036.277627,14824.165770,241.569,9.5,13.59,10.71,22.55,90.35,7.37,...,14.525,25.433333,16.733333,63.233333,1014.966667,14.966667,8.133333,3.505667,0,0
5,1027.0,15472.391289,14990.963816,248.073,9.0,12.89,11.37,23.06,165.52,-23.59,...,15.020,17.384615,10.576923,71.000000,1014.307692,12.576923,9.307692,4.474615,1,1
6,3168.0,16208.314757,15292.349860,254.277,7.8,11.95,10.37,23.52,81.95,-2.61,...,10.875,14.645161,9.129032,71.387097,1014.193548,13.451613,7.903226,2.393548,1,1
7,1153.0,17709.436967,16196.814474,260.500,5.7,11.82,10.73,24.52,70.34,-4.14,...,9.450,15.129032,7.870968,62.774194,1013.322581,14.516129,8.322581,4.998387,1,1
8,945.0,14613.991481,14551.024838,238.970,9.8,13.60,11.20,22.51,77.40,0.81,...,10.400,0.233333,-7.566667,57.600000,1014.533333,14.766667,11.633333,1.720667,0,2
9,681.0,16785.312189,15644.832268,258.504,7.2,11.88,10.13,24.16,90.09,-2.83,...,9.650,20.066667,11.500000,60.300000,1016.566667,14.666667,6.366667,2.497667,0,1

Creating Independent and Target features

In [12]:
Indpendent_features= Test_Data[['MonthlyNominalGDPIndexinMillion', 'MonthlyRealGDPIndexinMillion',
       'CPI', 'unemploymentrate',
       'CommercialBankInterestRateonCreditCardPlans',
       'FinanceRateonPersonalLoansatCommercialBanks24MonthLoan',
       'Earningsorwagesindollarsperhour',
       'CottonMonthlyPriceUScentsperPoundlbs', 'Changein',
       'Averageuplandplantedmillionacres',
       'Averageuplandharvestedmillionacres', 'yieldperharvestedacre',
       'Productionin480lbnetwerightinmillionbales',
       'Millusein480lbnetwerightinmillionbales', 'Exports', 'Tempavg',
       'DewPointavg', 'Humidityavg', 'SeaLevelPressavg', 'Visibilityavg',
       'Windavg', 'Precipsum', 'Event', 'FederalHoliday']]

In [13]:
Target_features=Test_Data[['SalesInThousandDollars']]

Normalising all the features

In [14]:
#defining a normalisation function 
def normalize (x): 
    return ( (x-np.min(x))/ (max(x) - min(x)))

In [15]:
# applying normalize ( ) to all columns 
Indpendent_features = Indpendent_features.apply(normalize)

Dropping columns which were removed from train data during feature selection method

In [16]:
Test_Data= Test_Data.drop(['Averageuplandharvestedmillionacres','Productionin480lbnetwerightinmillionbales',
                                                 'Tempavg','DewPointavg','Humidityavg', ], axis = 1)

In [17]:
Test_Data

,ProductCategory,SalesInThousandDollars,MonthlyNominalGDPIndexinMillion,MonthlyRealGDPIndexinMillion,CPI,unemploymentrate,CommercialBankInterestRateonCreditCardPlans,FinanceRateonPersonalLoansatCommercialBanks24MonthLoan,Earningsorwagesindollarsperhour,CottonMonthlyPriceUScentsperPoundlbs,...,Averageuplandplantedmillionacres,yieldperharvestedacre,Millusein480lbnetwerightinmillionbales,Exports,SeaLevelPressavg,Visibilityavg,Windavg,Precipsum,Event,FederalHoliday
0,MenClothing,1081.0,15740.544526,15148.822195,248.307,8.5,12.36,10.36,23.22,95.45,...,14.431,757,3.575,10.650,1020.633333,14.666667,9.533333,3.386333,2,2
1,WomenClothing,4481.0,17630.354586,16133.049427,261.074,5.9,11.82,10.73,24.50,73.38,...,10.818,790,3.775,9.450,1019.300000,14.900000,6.900000,1.042000,0,1
2,OtherClothing,1209.0,17053.738107,15841.758762,257.377,6.9,11.85,10.22,24.11,84.65,...,10.136,790,3.580,9.650,1021.400000,14.766667,10.033333,2.667333,0,2
3,WomenClothing,4294.0,17900.981857,16329.523792,259.647,5.4,11.98,9.85,25.04,69.35,...,10.845,781,3.625,10.250,1019.032258,12.935484,9.838710,3.868065,0,0
4,OtherClothing,897.0,15036.277627,14824.165770,241.569,9.5,13.59,10.71,22.55,90.35,...,10.700,831,3.370,14.525,1014.966667,14.966667,8.133333,3.505667,0,0
5,OtherClothing,1027.0,15472.391289,14990.963816,248.073,9.0,12.89,11.37,23.06,165.52,...,10.769,805,3.760,15.020,1014.307692,12.576923,9.307692,4.474615,1,1
6,WomenClothing,3168.0,16208.314757,15292.349860,254.277,7.8,11.95,10.37,23.52,81.95,...,12.121,782,3.375,10.875,1014.193548,13.451613,7.903226,2.393548,1,1
7,OtherClothing,1153.0,17709.436967,16196.814474,260.500,5.7,11.82,10.73,24.52,70.34,...,10.818,776,3.775,9.450,1013.322581,14.516129,8.322581,4.998387,1,1
8,OtherClothing,945.0,14613.991481,14551.024838,238.970,9.8,13.60,11.20,22.51,77.40,...,9.008,763,3.370,10.400,1014.533333,14.766667,11.633333,1.720667,0,2
9,MenClothing,681.0,16785.312189,15644.832268,258.504,7.2,11.88,10.13,24.16,90.09,...,10.136,777,3.480,9.650,1016.566667,14.666667,6.366667,2.497667,0,1

In [18]:
Test_Data.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 10 entries, 0 to 9
Data columns (total 21 columns):
 #   Column                                                  Non-Null Count  Dtype
---  ------                                                  --------------  -----
 0   ProductCategory                                         10 non-null     object
 1   SalesInThousandDollars                                  10 non-null     float64
 2   MonthlyNominalGDPIndexinMillion                         10 non-null     float64
 3   MonthlyRealGDPIndexinMillion                            10 non-null     float64
 4   CPI                                                     10 non-null     float64
 5   unemploymentrate                                        10 non-null     float64
 6   CommercialBankInterestRateonCreditCardPlans             10 non-null     float64
 7   FinanceRateonPersonalLoansatCommercialBanks24MonthLoan  10 non-null     float64
 8   Earningsorwagesindollarsperhour                         10 non-null     float64
 9   CottonMonthlyPriceUScentsperPoundlbs                    10 non-null     float64
 10  Changein                                                10 non-null     float64
 11  Averageuplandplantedmillionacres                        10 non-null     float64
 12  yieldperharvestedacre                                   10 non-null     int64
 13  Millusein480lbnetwerightinmillionbales                  10 non-null     float64
 14  Exports                                                 10 non-null     float64
 15  SeaLevelPressavg                                        10 non-null     float64
 16  Visibilityavg                                           10 non-null     float64
 17  Windavg                                                 10 non-null     float64
 18  Precipsum                                               10 non-null     float64
 19  Event                                                   10 non-null     int64
 20  FederalHoliday                                          10 non-null     int64
dtypes: float64(17), int64(3), object(1)
memory usage: 1.8+ KB

 product_category needs to be converted into numeric

In [19]:
## converting text data into numerical
Test_Data.replace({'MenClothing': 0, 'WomenClothing': 1,'OtherClothing':2},inplace=True)

In [20]:
# label_encoder
#label_encoder = preprocessing.LabelEncoder()

In [21]:
#Test_Data['ProductCategory']= label_encoder.fit_transform(Test_Data['ProductCategory'])

In [22]:
Test_Data

,ProductCategory,SalesInThousandDollars,MonthlyNominalGDPIndexinMillion,MonthlyRealGDPIndexinMillion,CPI,unemploymentrate,CommercialBankInterestRateonCreditCardPlans,FinanceRateonPersonalLoansatCommercialBanks24MonthLoan,Earningsorwagesindollarsperhour,CottonMonthlyPriceUScentsperPoundlbs,...,Averageuplandplantedmillionacres,yieldperharvestedacre,Millusein480lbnetwerightinmillionbales,Exports,SeaLevelPressavg,Visibilityavg,Windavg,Precipsum,Event,FederalHoliday
0,0,1081.0,15740.544526,15148.822195,248.307,8.5,12.36,10.36,23.22,95.45,...,14.431,757,3.575,10.650,1020.633333,14.666667,9.533333,3.386333,2,2
1,1,4481.0,17630.354586,16133.049427,261.074,5.9,11.82,10.73,24.50,73.38,...,10.818,790,3.775,9.450,1019.300000,14.900000,6.900000,1.042000,0,1
2,2,1209.0,17053.738107,15841.758762,257.377,6.9,11.85,10.22,24.11,84.65,...,10.136,790,3.580,9.650,1021.400000,14.766667,10.033333,2.667333,0,2
3,1,4294.0,17900.981857,16329.523792,259.647,5.4,11.98,9.85,25.04,69.35,...,10.845,781,3.625,10.250,1019.032258,12.935484,9.838710,3.868065,0,0
4,2,897.0,15036.277627,14824.165770,241.569,9.5,13.59,10.71,22.55,90.35,...,10.700,831,3.370,14.525,1014.966667,14.966667,8.133333,3.505667,0,0
5,2,1027.0,15472.391289,14990.963816,248.073,9.0,12.89,11.37,23.06,165.52,...,10.769,805,3.760,15.020,1014.307692,12.576923,9.307692,4.474615,1,1
6,1,3168.0,16208.314757,15292.349860,254.277,7.8,11.95,10.37,23.52,81.95,...,12.121,782,3.375,10.875,1014.193548,13.451613,7.903226,2.393548,1,1
7,2,1153.0,17709.436967,16196.814474,260.500,5.7,11.82,10.73,24.52,70.34,...,10.818,776,3.775,9.450,1013.322581,14.516129,8.322581,4.998387,1,1
8,2,945.0,14613.991481,14551.024838,238.970,9.8,13.60,11.20,22.51,77.40,...,9.008,763,3.370,10.400,1014.533333,14.766667,11.633333,1.720667,0,2
9,0,681.0,16785.312189,15644.832268,258.504,7.2,11.88,10.13,24.16,90.09,...,10.136,777,3.480,9.650,1016.566667,14.666667,6.366667,2.497667,0,1

Separating Independent features and Target feature

In [23]:
X=Test_Data.drop(['SalesInThousandDollars'],axis = 1)

In [24]:
X

,ProductCategory,MonthlyNominalGDPIndexinMillion,MonthlyRealGDPIndexinMillion,CPI,unemploymentrate,CommercialBankInterestRateonCreditCardPlans,FinanceRateonPersonalLoansatCommercialBanks24MonthLoan,Earningsorwagesindollarsperhour,CottonMonthlyPriceUScentsperPoundlbs,Changein,Averageuplandplantedmillionacres,yieldperharvestedacre,Millusein480lbnetwerightinmillionbales,Exports,SeaLevelPressavg,Visibilityavg,Windavg,Precipsum,Event,FederalHoliday
0,0,15740.544526,15148.822195,248.307,8.5,12.36,10.36,23.22,95.45,-8.82,14.431,757,3.575,10.650,1020.633333,14.666667,9.533333,3.386333,2,2
1,1,17630.354586,16133.049427,261.074,5.9,11.82,10.73,24.50,73.38,-0.84,10.818,790,3.775,9.450,1019.300000,14.900000,6.900000,1.042000,0,1
2,2,17053.738107,15841.758762,257.377,6.9,11.85,10.22,24.11,84.65,-5.26,10.136,790,3.580,9.650,1021.400000,14.766667,10.033333,2.667333,0,2
3,1,17900.981857,16329.523792,259.647,5.4,11.98,9.85,25.04,69.35,-0.70,10.845,781,3.625,10.250,1019.032258,12.935484,9.838710,3.868065,0,0
4,2,15036.277627,14824.165770,241.569,9.5,13.59,10.71,22.55,90.35,7.37,10.700,831,3.370,14.525,1014.966667,14.966667,8.133333,3.505667,0,0
5,2,15472.391289,14990.963816,248.073,9.0,12.89,11.37,23.06,165.52,-23.59,10.769,805,3.760,15.020,1014.307692,12.576923,9.307692,4.474615,1,1
6,1,16208.314757,15292.349860,254.277,7.8,11.95,10.37,23.52,81.95,-2.61,12.121,782,3.375,10.875,1014.193548,13.451613,7.903226,2.393548,1,1
7,2,17709.436967,16196.814474,260.500,5.7,11.82,10.73,24.52,70.34,-4.14,10.818,776,3.775,9.450,1013.322581,14.516129,8.322581,4.998387,1,1
8,2,14613.991481,14551.024838,238.970,9.8,13.60,11.20,22.51,77.40,0.81,9.008,763,3.370,10.400,1014.533333,14.766667,11.633333,1.720667,0,2
9,0,16785.312189,15644.832268,258.504,7.2,11.88,10.13,24.16,90.09,-2.83,10.136,777,3.480,9.650,1016.566667,14.666667,6.366667,2.497667,0,1

In [25]:
y=Test_Data['SalesInThousandDollars']

In [26]:
y

0    1081.0
1    4481.0
2    1209.0
3    4294.0
4     897.0
5    1027.0
6    3168.0
7    1153.0
8     945.0
9     681.0
Name: SalesInThousandDollars, dtype: float64

Load the model

In [27]:
os.chdir('C:\\Users\\Riyaz Mehendi\\OneDrive - CriticalRiver Technologies Pvt. Ltd\\Desktop\\Retail_Sales_Forecast\\src\\models')

In [28]:
# Load the model from the file
my_Model = joblib.load('TunedXGB_Model.pkl')

Using loaded model predicting on given test data

In [29]:
prediction=my_Model.predict(X)

In [30]:
prediction

array([1067.714  , 4424.0137 , 1240.5789 , 4143.192  ,  927.9188 ,
       1094.7936 , 2709.993  , 1155.2251 , 1052.8027 ,  834.10876],
      dtype=float32)

In [31]:
print(mean_absolute_percentage_error(y,prediction)*100)

6.7213775872824995