#### Importing Libraries and Reading Processed Data

In [1]:
import numpy as np
import pandas as pd
from sklearn import preprocessing
from sklearn.linear_model import LinearRegression
from sklearn.linear_model import Ridge
from sklearn.feature_selection import SelectKBest
from sklearn.svm import SVR
from sklearn.svm import LinearSVR
from xgboost import XGBRegressor
from sklearn.tree import DecisionTreeRegressor
from lightgbm import LGBMRegressor
from sklearn.ensemble import RandomForestRegressor
from sklearn.model_selection import GridSearchCV, StratifiedKFold
from statsmodels.stats.outliers_influence import variance_inflation_factor
from sklearn.datasets import make_regression
from sklearn.model_selection import cross_val_score
from sklearn.model_selection import RepeatedKFold
from sklearn import preprocessing
from sklearn.metrics import mean_absolute_percentage_error
from sklearn.model_selection import train_test_split
import re
import warnings
warnings.filterwarnings("ignore")
import time
import os
import joblib

C:\Users\Riyaz Mehendi\anaconda3\envs\venv1\lib\site-packages\xgboost\compat.py:36: FutureWarning: pandas.Int64Index is deprecated and will be removed from pandas in a future version. Use pandas.Index with the appropriate dtype instead.
  from pandas import MultiIndex, Int64Index

In [2]:
os.getcwd()

'C:\\Users\\Riyaz Mehendi\\OneDrive - CriticalRiver Technologies Pvt. Ltd\\Desktop\\Retail_Sales_Forecast\\src\\models'

In [3]:
project_path='C:\\Users\\Riyaz Mehendi\\OneDrive - CriticalRiver Technologies Pvt. Ltd\\Desktop\\Retail_Sales_Forecast'
processed_data='data\\processed'
processed_file_name='Cleaned_data.csv'

In [4]:
processed_file_path=os.path.join(project_path,processed_data,processed_file_name)

In [5]:
## reading the data
Data=pd.read_csv(processed_file_path)

In [6]:
Data

,ProductCategory,SalesInThousandDollars,MonthlyNominalGDPIndexinMillion,MonthlyRealGDPIndexinMillion,CPI,unemploymentrate,CommercialBankInterestRateonCreditCardPlans,FinanceRateonPersonalLoansatCommercialBanks24MonthLoan,Earningsorwagesindollarsperhour,CottonMonthlyPriceUScentsperPoundlbs,...,Averageuplandplantedmillionacres,yieldperharvestedacre,Millusein480lbnetwerightinmillionbales,Exports,SeaLevelPressavg,Visibilityavg,Windavg,Precipsum,Event,FederalHoliday
0,1,1746.60251,14844.531193,14724.200153,240.529,9.9,14.26,10.83,22.53,88.09,...,9.008,747,3.47,11.365,1013.166667,14.466667,10.200000,2.532000,1,0
1,2,1035.00000,15185.628947,14896.674813,241.960,9.8,13.44,10.94,22.69,155.47,...,10.829,814,3.42,15.275,1018.700000,14.833333,10.100000,1.820667,0,2
2,1,3071.00000,15219.059036,14945.427088,241.981,9.4,13.59,10.71,22.70,126.55,...,10.829,835,3.57,15.025,1011.766667,14.166667,10.200000,4.158000,1,1
3,1,2521.00000,14590.432252,14559.410173,238.777,9.9,13.60,11.20,22.44,71.78,...,8.989,767,3.37,9.950,1019.033333,14.666667,11.133333,1.364333,0,2
4,2,865.00000,14424.284901,14435.812509,238.282,9.6,13.71,10.89,22.16,64.26,...,8.905,809,3.47,9.700,1015.967742,14.483871,6.806452,3.466774,0,0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
247,1,2919.00000,15117.467110,14878.546983,241.485,9.5,13.59,10.71,22.60,104.73,...,10.829,833,3.57,15.025,1014.551724,13.862069,8.862069,3.101034,0,1
248,2,1144.00000,16433.882719,15435.675103,256.234,7.7,11.94,10.12,23.90,89.71,...,12.077,849,3.38,11.750,1015.000000,13.107143,11.392857,3.856071,1,1
249,1,2371.00000,14424.284901,14435.812509,238.282,9.6,13.71,10.89,22.16,64.26,...,8.905,809,3.47,9.700,1015.967742,14.483871,6.806452,3.466774,0,0
250,0,524.00000,14421.752895,14407.053343,233.402,7.8,12.03,11.44,22.05,57.70,...,9.296,799,4.17,11.550,1015.967742,14.000000,12.000000,2.443226,0,2
251,0,718.00000,16521.133927,15529.835696,255.967,7.6,11.94,10.12,23.92,92.54,...,12.077,862,3.38,12.225,1019.862069,15.103448,10.034483,1.148276,0,0

#### Train test split

Separating independent features and target feature

In [7]:
X= Data.drop(['SalesInThousandDollars'],axis=1)

In [8]:
X

,ProductCategory,MonthlyNominalGDPIndexinMillion,MonthlyRealGDPIndexinMillion,CPI,unemploymentrate,CommercialBankInterestRateonCreditCardPlans,FinanceRateonPersonalLoansatCommercialBanks24MonthLoan,Earningsorwagesindollarsperhour,CottonMonthlyPriceUScentsperPoundlbs,Changein,Averageuplandplantedmillionacres,yieldperharvestedacre,Millusein480lbnetwerightinmillionbales,Exports,SeaLevelPressavg,Visibilityavg,Windavg,Precipsum,Event,FederalHoliday
0,1,14844.531193,14724.200153,240.529,9.9,14.26,10.83,22.53,88.09,2.68,9.008,747,3.47,11.365,1013.166667,14.466667,10.200000,2.532000,1,0
1,2,15185.628947,14896.674813,241.960,9.8,13.44,10.94,22.69,155.47,22.85,10.829,814,3.42,15.275,1018.700000,14.833333,10.100000,1.820667,0,2
2,1,15219.059036,14945.427088,241.981,9.4,13.59,10.71,22.70,126.55,20.83,10.829,835,3.57,15.025,1011.766667,14.166667,10.200000,4.158000,1,1
3,1,14590.432252,14559.410173,238.777,9.9,13.60,11.20,22.44,71.78,7.42,8.989,767,3.37,9.950,1019.033333,14.666667,11.133333,1.364333,0,2
4,2,14424.284901,14435.812509,238.282,9.6,13.71,10.89,22.16,64.26,-0.83,8.905,809,3.47,9.700,1015.967742,14.483871,6.806452,3.466774,0,0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
247,1,15117.467110,14878.546983,241.485,9.5,13.59,10.71,22.60,104.73,15.92,10.829,833,3.57,15.025,1014.551724,13.862069,8.862069,3.101034,0,1
248,2,16433.882719,15435.675103,256.234,7.7,11.94,10.12,23.90,89.71,4.91,12.077,849,3.38,11.750,1015.000000,13.107143,11.392857,3.856071,1,1
249,1,14424.284901,14435.812509,238.282,9.6,13.71,10.89,22.16,64.26,-0.83,8.905,809,3.47,9.700,1015.967742,14.483871,6.806452,3.466774,0,0
250,0,14421.752895,14407.053343,233.402,7.8,12.03,11.44,22.05,57.70,4.02,9.296,799,4.17,11.550,1015.967742,14.000000,12.000000,2.443226,0,2
251,0,16521.133927,15529.835696,255.967,7.6,11.94,10.12,23.92,92.54,-2.02,12.077,862,3.38,12.225,1019.862069,15.103448,10.034483,1.148276,0,0

In [9]:
y= Data['SalesInThousandDollars']

In [10]:
y

0      1746.60251
1      1035.00000
2      3071.00000
3      2521.00000
4       865.00000
          ...
247    2919.00000
248    1144.00000
249    2371.00000
250     524.00000
251     718.00000
Name: SalesInThousandDollars, Length: 252, dtype: float64

Splitting data intp train-test with 75% and 25% ratio

In [11]:
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.25, random_state=42, shuffle = False)

In [12]:
print(X_train.shape)
print(y_train.shape)
print(X_test.shape)
print(y_test.shape)

(189, 20)
(189,)
(63, 20)
(63,)

In [13]:
X_train.dtypes

ProductCategory                                             int64
MonthlyNominalGDPIndexinMillion                           float64
MonthlyRealGDPIndexinMillion                              float64
CPI                                                       float64
unemploymentrate                                          float64
CommercialBankInterestRateonCreditCardPlans               float64
FinanceRateonPersonalLoansatCommercialBanks24MonthLoan    float64
Earningsorwagesindollarsperhour                           float64
CottonMonthlyPriceUScentsperPoundlbs                      float64
Changein                                                  float64
Averageuplandplantedmillionacres                          float64
yieldperharvestedacre                                       int64
Millusein480lbnetwerightinmillionbales                    float64
Exports                                                   float64
SeaLevelPressavg                                          float64
Visibilityavg                                             float64
Windavg                                                   float64
Precipsum                                                 float64
Event                                                       int64
FederalHoliday                                              int64
dtype: object

#### Model Building

XGBoost Model

In [14]:
regressor = XGBRegressor(random_state=42)
model = regressor.fit(X_train, y_train)
y_pred = model.predict(X_test)

In [15]:
print(mean_absolute_percentage_error(y_test,y_pred)*100)

17.043785097270572

Hyper-parameter tuning the XGBoost Model with CrossValidation

In [16]:
model.get_params()

{'objective': 'reg:squarederror',
 'base_score': 0.5,
 'booster': 'gbtree',
 'colsample_bylevel': 1,
 'colsample_bynode': 1,
 'colsample_bytree': 1,
 'enable_categorical': False,
 'gamma': 0,
 'gpu_id': -1,
 'importance_type': None,
 'interaction_constraints': '',
 'learning_rate': 0.300000012,
 'max_delta_step': 0,
 'max_depth': 6,
 'min_child_weight': 1,
 'missing': nan,
 'monotone_constraints': '()',
 'n_estimators': 100,
 'n_jobs': 8,
 'num_parallel_tree': 1,
 'predictor': 'auto',
 'random_state': 42,
 'reg_alpha': 0,
 'reg_lambda': 1,
 'scale_pos_weight': 1,
 'subsample': 1,
 'tree_method': 'exact',
 'validate_parameters': 1,
 'verbosity': None}

In [17]:
param_grid = dict(
    n_jobs=[16],
    learning_rate=[0.1, 0.5],
    objective=['reg:squarederror'],
    max_depth=[5, 10, 15], 
    n_estimators=[100, 200, 500],
    subsample=[0.2, 0.8, 1.0],
    gamma=[0.05, 0.5],
    scale_pos_weight=[0, 1],
    reg_alpha=[0, 0.5],
    reg_lambda=[1, 0],
)

In [18]:
model = XGBRegressor(random_state=42, verbosity=1)

grid_search = GridSearchCV(estimator=model,
                           param_grid=param_grid,
                           scoring='neg_mean_absolute_percentage_error',
                           )

In [19]:
%%time
best_model = grid_search.fit(X_train, y_train)
print('Optimum parameters', best_model.best_params_)

Optimum parameters {'gamma': 0.05, 'learning_rate': 0.1, 'max_depth': 5, 'n_estimators': 100, 'n_jobs': 16, 'objective': 'reg:squarederror', 'reg_alpha': 0.5, 'reg_lambda': 1, 'scale_pos_weight': 0, 'subsample': 0.8}
CPU times: total: 2h 44min 41s
Wall time: 36min 24s

In [20]:
ModelXGBregressor = XGBRegressor(gamma=0.5, learning_rate= 0.1, max_depth= 5, n_estimators= 100,
                         n_jobs=16, objective='reg:squarederror', reg_alpha= 0.5, reg_lambda= 1, 
                         scale_pos_weight=0, subsample=1.0,random_state=42)

In [21]:
TunedXGBmodel = ModelXGBregressor.fit(X_train, y_train)
tuned_xgboost_pred = TunedXGBmodel.predict(X_test)

In [22]:
print(mean_absolute_percentage_error(y_test,tuned_xgboost_pred)*100)

17.514643501344317

#### Saving the model

In [23]:
os.getcwd()

'C:\\Users\\Riyaz Mehendi\\OneDrive - CriticalRiver Technologies Pvt. Ltd\\Desktop\\Retail_Sales_Forecast\\src\\models'

In [24]:
 # Save the model as a pickle in a file
joblib.dump(TunedXGBmodel, 'TunedXGB_Model.pkl')
 
# Load the model from the file
Tuned_XGB_Model_from_joblib = joblib.load('TunedXGB_Model.pkl')